### ISSUE TITLE
Basic question

### ISSUE THREAD

**Issue by hash55** [jshumphrey/f1db#1]
Hello! First of all just thank you for this module that looks amazing.
I'm quite new to these world, and I would like to know what is the "proper" way to do some basic functions. For example, how could I access LapTimes from a race from 2012.? (if that is possible).

Thanks in advance

**Comment by jshumphrey** [comment]
@hash55 The script manages a SQL database of the various kinds of race data, such as the lap times. Once the script generates the SQLite database, you could query the database directly with a program you write yourself, or you could use the menu items to write your own queries or SELECT statements to retrieve data, or you could create your own SQL script files to query the tables and export data out.

But you'll definitely need at least a basic understanding of SQL in order to make use of the data here.
